# Dockerfile.dev
FROM ruby:3.4

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nano \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /app

ENV BUNDLE_PATH=/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3 \
    BUNDLE_APP_CONFIG="/bundle"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0"]